### ISSUE TITLE
Unknown transaction type, cannot parse

### ISSUE THREAD

**Issue by jonblack** [WoLpH/mt940#1]
I'm getting the exception `Unknown transaction type, cannot parse` in the following line https://github.com/WoLpH/mt940/blob/master/mt940/parser.py#L178.

The MT940 file contains the following line:

    :86:ABN AMRO BANK N.V.               YP PAKKET                   3,10

So it would seem that the additional information line (86) doesn't always fit the formats you're expecting. Perhaps the default case just just set the value to the entire contents of the line if it can't be parsed?

**Comment by WoLpH** [comment]
*bump* are you still there @jonblack?

**Comment by WoLpH** [comment]
Probably fixed with the latest release, if not. Let me know :)
