### ISSUE TITLE
AttributeError: module 'mt940' has no attribute 'parse'

### ISSUE THREAD

**Issue by ragflyer** [wolph/mt940#100]
Hello,

On Python 3.9.5 I get the above error when I run one of the examples. Any hints on what I do wrong?

Kind regards

**Comment by wolph** [comment]
Usually it's either due to having a different library installed that uses the `mt940` name, or you have a `mt940.py` file that is getting imported.

To see which is the case, try this:
```python
import mt940
print(mt940)
```

**Comment by JonathanNEMRY** [comment]
@wolph  I am pretty sure that this is the same error that I reported...does anything is planned to fix this?

**Comment by wolph** [comment]
> @wolph I am pretty sure that this is the same error that I reported...does anything is planned to fix this?

The error is not in the library, it's on your end so there is nothing I can do to fix it.

**Comment by JonathanNEMRY** [comment]
@wolph  it is a library that parse mt940...and if we feed it with mt940 it crashes...hard to believe it is not into the library that the bug is....sad to have to make workaround for something that is well made.

**Comment by wolph** [comment]
Can you share the code that you are using?

There could be something I overlooked of course but I've only ever seen
this error in case of conflicting modules or files.

**Comment by ragflyer** [comment]
I fixed it by uninstalling all mt940 related libraries and reinstalling mt940. It seems it was not related to your code, sorry for the inconvenience.
