### ISSUE TITLE
Dropping Transaction Data?

### ISSUE THREAD

**Issue by aodhan-domhnaill** [wolph/mt940#104]
I'm translating this to Golang, but I'm confused by the below code.

https://github.com/wolph/mt940/blob/026859d7dcfef60578cc019fe90fda51102c07c5/mt940/models.py#L455-L463

This is the only place I see you appending `Transactions`, but is seems like you would lose the transaction data since you overwrite before appending.

Am I missing something?

**Comment by wolph** [comment]
Python uses pass-by-reference and that is the only place a `Transaction` object is created.
Simply put, the `transaction` variable and `self.transactions[-1]` (after appending) are the same object.

The code could use some refactoring to be clearer but it works correctly.
- The 3 lines at the top only apply the very first time a transaction is created.
- The second if applies only if there is an existing transaction object and that object is already finished, i.e. has an `id`
