### ISSUE TITLE
AssertionError: Unknown tag 90in line: ':90D:'

### ISSUE THREAD

**Issue by batjko** [WoLpH/mt940#11]
Hi there,

I get the above error when running through some of my messages, which of cause is an exception failing the parse method.

I don't need this field, I just need 25 and 62, so ideally, I'd just like to be able to ignore those unknown fields.

What can I do?

Many thanks.

**Comment by batjko** [comment]
I just noticed that this is a tag that only exists in MT941s.

Any way of testing first whether the message at hand is indeed MT940?

**Comment by WoLpH** [comment]
Not sure how to tell the difference really (this is the first time I hear about MT941 to be honest).

You could work around this issue fairly easy though:
```python
import mt940

class Tag90(mt940.tags.Tag):
    id = 90
    pattern = r'.*'

mt940.tags.TAG_BY_ID[Tag90.id] = Tag90
```

**Comment by batjko** [comment]
Ah ok. that'll help make it more stable since we do get the occasional MT941 as statements and there's no clue in the file name. 

So I'll use this for any unknown tags I can find.
Thanks for that!
