### ISSUE TITLE
Falsely recognizes tags in a time value (field 86)

### ISSUE THREAD

**Issue by batjko** [WoLpH/mt940#12]
Hi,

I just found that if tag 86 contains a time formatted like `hh:mm:ss` the `:mm:` portion will be recognized as a tag and if incidentally that *minute* portion is not an actual tag, it will freak out:

Here's an excerpt of the message in question. Note the time portion in the first 86 tag:
```
:61:1507160716CD7500,00FMSC1971033191//IA004587508020
NONEREF
:86:eDeposit in Branch/Store 07/16/15 10:33:22 AM 1800 S NEVADA AVE C
OLORADO SPRINGS CO 5133
:61:1507160716DD8000,00FCHK4201//IA008510335677
NONEREF
:86:CHECK
:62F:C150716USD706403,50
:64:C150716USD706403,50
:65:C150717USD706403,50
```
Results in:
`AssertionError: Unknown tag 33in line: ':33:'`

**Comment by WoLpH** [comment]
That's a nice one, apparently (some of) the regexes don't look for the tag at the beginning of the line... that's a bit silly. Shouldn't be too hard to fix

**Comment by batjko** [comment]
Thanks for your quick responses!
This module is super helpful for what I am trying to do! :+1:

**Comment by WoLpH** [comment]
Took a while to actually fix it. But it's released now :)

**Comment by batjko** [comment]
Awesome! I'll update and try it out.
Thanks.
