### ISSUE TITLE
Differentiating between 62M and 62F

### ISSUE THREAD

**Issue by batjko** [WoLpH/mt940#13]
Hi there,

Sorry, I got another one:

I can see in the [docs](http://mt940.readthedocs.org/en/latest/mt940.html#mt940.tags.ClosingBalance.id), that the field 62 is the "closing_balance". However that's not always true, as that would only be the case for 62**F**, while often there may be intra-day balances with  field 62**M**.

Does this field not see a difference between the two or is there some magic going on that already works with 62F only?

Thanks very much.

**Comment by WoLpH** [comment]
The latest release (v3.2) adds support for other types of balances such as `final_closing_balance` :)
