### ISSUE TITLE
Parsing error: "type 'exceptions.AttributeError'"

### ISSUE THREAD

**Issue by batjko** [WoLpH/mt940#14]
This is an error introduced by the fix in 08f52ab.

As mentioned in #12, I upgraded the package, but now I'm getting the following error for every file it tries to parse:

`<type 'exceptions.AttributeError'>`

Not sure where it occurs or why.
Let me know what I can get you to help pinpoint this regression.

Cheers.

**Comment by WoLpH** [comment]
Do you have a stacktrace by any chance?

I have absolutely no clue what is going wrong in your case but completely uninstalling the old package (just trash the entire directory: `python -c 'import os, mt940; print os.path.abspath(mt940.__file__)'`) might help.

**Comment by batjko** [comment]
I didn't remove the old version, just upgraded. I'll try that and see if I
can get more of the stack trace if it fails again.
