### ISSUE TITLE
Extra Details?

### ISSUE THREAD

**Issue by waynestanton** [WoLpH/mt940#16]
I cannot see how to get the extra details from any mt940 file.  I understood extra_details to be the optional text line at the end of the :61 block.  I could be missing something obvious, but can you please tell how to get the text "FT148090949341           FOREIGN U" from the example mt940 block below? 

:61:1404010401D1,NMSCNONREF
FT148090949341           FOREIGN U
:86:SD

What I get back is:
{'amount': <-1 EUR>,
 'bank_reference': None,
 'currency': 'EUR',
 'customer_reference': 'NONREF',
 'date': Date(2014, 4, 1),
 'entry_date': Date(2014, 4, 1),
 'extra_details': '',
 'funds_code': None,
 'id': 'NMSC',
 'status': 'D',
 'transaction_details': 'SD'}

**Comment by WoLpH** [comment]
It looks like you've found a bug, I'll investigate further :)

**Comment by waynestanton** [comment]
Just wanted to check to see what you have found?  Any luck resolving this issue?

**Comment by WoLpH** [comment]
Sorry Wayne, I've just been crazy busy so it's taking me far longer to respond.

You have indeed found a bug and I have a fix for the bug, but the fix broke some of the tests so I'm not entirely ready to push out a new release just yet. I should be able to take care of it soon (within 2 weeks) though.

**Comment by WoLpH** [comment]
I believe it's fixed now. Can you try with the current develop release @waynestanton?

**Comment by WoLpH** [comment]
There is a new release incorporating this change now :)

**Comment by waynestanton** [comment]
Thanks very much for fixing that.  Sorry to take so long to get back to you.  Results look good.
