### ISSUE TITLE
incorrect entry date for :61: statement line 

### ISSUE THREAD

**Issue by benkonrath** [WoLpH/mt940#17]
Thanks for this library - it's really useful!

I found a problem with the entry date from in a mutation line from an ABN AMRO (NL) MT940 file. This line seems to be parsed incorrectly:

```
:61:1412310105C**,**N570NONREF
```

The entry date should be 5 Jan 2015, not 5 Jan 2014 as shown here:

```
'customer_reference': 'NONREF',
 'date': Date(2014, 12, 31),
 'entry_date': Date(2014, 1, 5),
```

Since the entry date doesn't have a year, I wonder if it should always be assumed to be in the future. Any thoughts on this? Thanks.

**Comment by WoLpH** [comment]
The format after the `:61:` should look like `6!n[4!n]2a[1!a]15d1!a3!c16x[//16x]` according to the standard: http://www.sepaforcorporates.com/swift-for-corporates/account-statement-mt940-file-format-overview/

In your case the 141231 indicates year 14, month 12 and date 31. The 0105 would be the entry date in months. If it's somehow incorrect than either the standard that I used is incorrect or the ABN AMRO doesn't follow the standard. Both are possible since all banks seem to have their own interpretation

**Comment by benkonrath** [comment]
The statement line in the ABN AMRO MT940 file is correctly formatted. The transaction date is 31 Dec 2014 and the entry date is 5 Jan 2015 as verified in the bank account in question. The problem is about how the entry date is interpreted by this library.

The entry date 0105 is trying to indicate that it has entered on 5 Jan 2015 the but there's no way to indicate that in the format since the entry date is only 4 digits (MMDD). This library assumes that the entry date year is the same as the transaction date year sets it to 5 Jan 2014.

Wouldn't it be better assume that the entry date always be the same as the value date or a date in the future? In this case you can see that the entry date being 11 months before the value date isn't reasonable.

**Comment by WoLpH** [comment]
If the entry date is always after the regular date, than that might be a good idea. I'll have to check some files to see if that's the case :)
Alternatively I'll have to make a method that tries both and uses the smallest delta

**Comment by benkonrath** [comment]
Ok, thanks.

**Comment by benkonrath** [comment]
It's not always the case that entry date comes after the value date. I just saw this in a Knab STA file:
```
:61:1604010331C0,99NTRFNONREF//B6C31INZKL0ZDE4S
```
I like your suggestion about trying both dates and using the smallest delta. I suppose that logic would only need to kick in when the entry date comes before the value date.

**Comment by benkonrath** [comment]
I can make a PR for this but I'll only have time in a few weeks.

**Comment by WoLpH** [comment]
Let's just see who has time the earliest :)

I'm still a bit swamped but it's getting less for me

**Comment by WoLpH** [comment]
I've just pushed out a new release which incorporates all of your other pull requests as well. I haven't started on this one yet but I might soon :)

**Comment by rjroos** [comment]
Hi,

I just ran into this problem myself in a java mt940 parser. I'm afraid the closest delta won't work.
This is a mt940 file from ING bank where a sepa direct debit payment was made on 03-03-2015 and the money disputed and returned on 03-30-2016:
 
:60F:C160229EUR00000,00
...
:61:1503030330D10,00NRTIEREF//16090424691081
...
:62F:C160331EUR00000,00

The strategy I was thinking about is to record the dates from :61: and :62: and go from there.

Regards,
Robbert-Jan

**Comment by WoLpH** [comment]
That might be the best solution... the MT940 standard is really not defined (or implemented) well enough it seems...

Every bank has it's own standards :(

**Comment by benkonrath** [comment]
I think this is more about the standard not being sufficient for our use. It really should be a full date - I have no idea why MT940 requires only  the month and day. In any case, we should be able to find a workaround. We have some real world test data to work from so that helps a lot.

**Comment by rjroos** [comment]
I think it's impossible to do it correctly and you'll have to start guessing somewhere.

When I download 3 years of mt940 the file will be:

:60F:C160101...
:61:150303 0330 ....
:61:140303 0330 ....
:61:130303 0330 ....
:62F:C130101...

So start: 01-01-2013, end: 01-01-2016 and 3 transactions, which have value-date of 3-3-[2013,2014,2015]. They all have a transaction date of March 30. I think it's possible to know if the 3rd transaction has a transaction date of 30-3-2013 or 30-3-2014.

Let's hope the mt940 disappears soon in favor of CAMT053 :-(

**Comment by wieslawmlynarski** [comment]
HI,
So I wrote in the past mt940 parsers, and I had the same issue with the dates.
And I implemented that only for decemeber and january, assuming that statements are daily.
Because the entry_date might be next year.
So if value date (date) month is 12 and entry date month is 01 I add +1 year to entry date.
What they are writing on swift specification
https://www2.swift.com/uhbonline/books/public/en_uk/usgf_20160722/index.htm?subpage=mt940-11-field-86.htm

> The SWIFT System validates subfield 2, Entry Date (Date in reduced ISO form), using current System Year (Error code(s): T50).
So you can also assume the user will interpret the date him self. or use the opening or closing balance date.

@rjroos for me when you download a statement for 3 years it looks more like mt942 operation history format. I think the general case is that statements are generated per day/month. because it does not give any value to provide bank statements every 3 years.

**Comment by FelixSchwarz** [comment]
How about not guessing at all? Maybe return a custom class if the date is missing? So every caller could do their own heuristics?
In general I'd really like to have an API which just reflects "reality" (the actual data) without any guessing. If you want to provide some "helpers" maybe extend the custom class with something like "guessed_year".

(sorry if I did not understand the issue at hand/if it distracts from actually finding a good solution.)

**Comment by WoLpH** [comment]
That might be a better option, at one point I was hoping a good solution was available but apparently there isn't.

**Comment by jelle-eastground** [comment]
I was experiencing similar problems with this :61: statement line:

`:61:1901011231C1`

The parsed entry_date returned by this library was 2019-12-31 and should obviously be 2018-12-31. I'd like to suggest something like this:

```
def get_processed_entry_date(date, entry_date):
    if date > entry_date and (date-entry_date).days >= 330:
        return entry_date+relativedelta(years=1)
    elif entry_date > date and (entry_date-date).days >= 330:
        return entry_date - relativedelta(years=1)

    return entry_date
```

This seems to be OK in almost all cases. I think it is at least much better than just adopting the year of the date as entry_date year.

**Comment by WoLpH** [comment]
The new release implements the code created by @jelle-eastground:

https://github.com/WoLpH/mt940/blob/fef4a678199fb91281a57c65235f71d10970e013/mt940/tags.py#L322-L326

Feel free to try and let me know if it needs to be improved.
