### ISSUE TITLE
ING mt940 export assertionError

### ISSUE THREAD

**Issue by sphaero** [WoLpH/mt940#2]
```
Traceback (most recent call last):
  File "mt940parse.py", line 5, in <module>
    for transaction in transactions:
  File "mt940/mt940/parser.py", line 21, in __iter__
    for transaction in Transaction.parse(transaction_collection):
  File "mt940/mt940/parser.py", line 81, in parse
    assert len(transactions) == len(transactions_detail)
AssertionError
```

**Comment by WoLpH** [comment]
The assert is there to make sure everything is being read correctly, apparently you have a transaction without details or details without a transaction.

Can you send me a (anonymized) version of your MT940 file so I can add support for your file?

**Comment by sphaero** [comment]
Sorry these 940's are too big to anonymize unless you know an automatic way. I've found mt-940 to parse them correctly

**Comment by WoLpH** [comment]
Well, to support it I would need a basic example of where it goes wrong of
course :)

**Comment by sphaero** [comment]
It could be because ING adds a :86 field to the end balance. I'm running into an issue with mt-940 as well:
https://code.google.com/p/mt940/issues/detail?id=4

for example the tail of an ing mt940 looks like:
```
:61:1401060106C1597,20NTRFEREF//14006711073704
/TRCD/00100/
:86:/EREF/131224RABONL2U0001800002000006//CNTP/NL92RABO0xxxxxxx/RABONL2U/*******///REMI/USTD//000060/
:62F:C141231EUR12820,07
:64:C141231EUR12820,07
:65:C150101EUR12820,07
:65:C150102EUR12820,07
:86:/SUM/75/7/9740,23/13560,34/
-}
```
In your code this would cause the assertion error since there is one more detail field than transaction fields

**Comment by WoLpH** [comment]
Hmm... so it's an open-ended version of `:86:`, this is different from what certain other providers claim to be the standard.

Regardless, I'll just remove the assertion, it was more of a sanity check anyhow.
