### ISSUE TITLE
What  about to pass `data`directly?

### ISSUE THREAD

**Issue by philippeowagner** [WoLpH/mt940#24]
What about to pass `data` directly to [`parse(...)`](https://github.com/WoLpH/mt940/blob/develop/mt940/parser.py#L32 )? Eg. testing for a no file path string or to add a `data` argument with default value `=None`.
We load the data from a database model and parse `data` on demand, so we do not use or have files. We could provide the PR if you like to merge it. 

Thanks for sharing the library and maintaining it! 👍

**Comment by WoLpH** [comment]
I wouldn't mind merging it but I don't see much benefit to be honest.

The current version would be:
```
transactions = mt940.models.Transactions()
transactions.parse(data)
```

Which means it would only save you a single line. Is it worth it? :P

**Comment by philippeowagner** [comment]
I went through all the lines of the library. Anyway, thanks for your hint about the internal of mt940 ;-)

It's not about saving a line or two it's more to have an "single, input agnostic interface" to the mt940 library, `parse()` in this case. 

What do you think? Is it worth it??

**Comment by WoLpH** [comment]
I suppose that's fair :)

If you're willing to create a pull request I'm all for it. It would certainly help to make a nice and clear interface.

**Comment by WoLpH** [comment]
The new release has been published. Thanks for your help :)
