### ISSUE TITLE
`transaction_reference` only present in the first transaction.

### ISSUE THREAD

**Issue by philippeowagner** [WoLpH/mt940#26]
The `transaction_reference` is only in the first transaction - and empty in all others.

Having the following swift file:

```
:20:2016101714551876
.....
:61:1610171017C123,FMSC01008//NONREF
20161014001442003300234000000XXX
:86:1017?61GIRO AUS KONTO XX-XXXXX-X NAME-XXXXX MARTIN UND XXXXXX M
USTERSTRASSE 123 4000 BASEL
:61:1610171017C123,FMSC01008//NONREF
20161014001442003300234000000XXX
:86:1017?61GIRO AUS KONTO XX-XXXXX-X NAME-XXXXX MARTIN UND XXXXXX M
USTERSTRASSE 123 4000 BASEL
:61:1610171017C123,FMSC01008//NONREF
20161014001442003300234000000XXX
:86:1017?61GIRO AUS KONTO XX-XXXXX-X NAME-XXXXX MARTIN UND XXXXXX M
USTERSTRASSE 123 4000 BASEL
```

Will result in... 

```
>>> t[0].data.get('transaction_reference')
'2016101714551876'
>>> t[1].data.get('transaction_reference')
>>> t[2].data.get('transaction_reference')
```

Shouldn't the `transaction_reference` be part of each transaction record?

**Comment by WoLpH** [comment]
Perhaps I've misinterpreted how the `transaction_reference` is used but I was under the impression it was specific to a single transaction.

Upon further reflection, I believe I was incorrect :)
Can you try the latest development?

**Comment by WoLpH** [comment]
These changes are now in the latest production release so I hope they work for everyone.
