### ISSUE TITLE
Parse transaction_details

### ISSUE THREAD

**Issue by nomoketo** [WoLpH/mt940#30]
Are there any plans to parse the contents of the transaction_details field?

A description of one of the possible formats that also frequently appears in your test files can be found here: https://www.db-bankline.deutsche-bank.com/download/MT940_Deutschland_Structure2002.pdf

**Comment by WoLpH** [comment]
The problem is that these are highly dependent on the bank. Every bank has it's own implementation and some banks even have several different implementations which makes it nearly impossible to automatically detect and parse the specific version.

One solution would be to create a processor to take care of this: https://mt940.readthedocs.io/en/latest/mt940.html#module-mt940.processors
I have no objections to accepting processor pull requests so people can enable this type of processing but enabling it by default is probably not feasible. They're fairly easy to use though: https://github.com/WoLpH/mt940/blob/develop/tests/test_processors.py#L56-L64

**Comment by nomoketo** [comment]
It seems/seemed to me that the Deutsche Bank one is one of two structured/standardized options.

Anyway, is a processor really the right choice? It seems to me that a processor can not new fields to the transaction. Should it just replace the transaction_details value with another object containg the parsed details?

**Comment by WoLpH** [comment]
Well, if it's an easily recognizable and common (i.e. supported by a few large banks) then I would have no problem making it a default.

As for adding new fields, that's no problem at all. Just look at the source: https://mt940.readthedocs.io/en/latest/_modules/mt940/processors.html
The `tag_dict` is mutable so you can easily add/modify/remove fields as you wish.

**Comment by nomoketo** [comment]
Well, i wrote a parser for the format that my bank (Triodos) uses and it's the same one that Deutsche Bank is describing in their document and that is appearing frequently in your test files. There seems wo be one other one (often called „structured“, something with slashes or something) and the option to not have a format in it at all. I'm not sure yet how to differentiate between them but it should be possible. 

And thanks for the example, now I see. I'm going to try writing something. :)

**Comment by WoLpH** [comment]
Any progress? Need help? :)

**Comment by sweh** [comment]
Hi WoLpH,

I wrote a post_processor for transaction_details and made a PullRequest into the `fints` package. That does not seem to be the best place. Can you have a look at it and tell me if I can integrate it into you package?

Kind regards,
  Sebastian

**Comment by NotANormalNerd** [comment]
Hello at all,

I was just trying to figure something out for our daily business and came across this fix.
I have some questions regarding the implementation @sweh 

Why did you filter on only the GVCs specified? It seems there are potentially 999 GVCs available:
https://www.kontopruef.de/mt940s.shtml

Would it be advisable to leave those out?

Thanks for your reply

**Comment by WoLpH** [comment]
That actually looks a lot better, perhaps I should incorporate that into the code. The new release isn't working yet anyhow so everything can still be changed with regards to the transaction details parsing :)

**Comment by NotANormalNerd** [comment]
I forked the repo and just removed the GVC Check.
Works well for me. But I see there are Tests failing. I will have a look if I can get some time aside.

**Comment by WoLpH** [comment]
I've created a new release which works great for all files I've been able to test but it still includes the GVC check. Please let me know if you notice any issues :)

**Comment by sweh** [comment]
Looks good. Thanks a lot!!!
