### ISSUE TITLE
Wrong reprtitions count in TransactionDetails tag

### ISSUE THREAD

**Issue by sq9mev** [WoLpH/mt940#37]
```
class TransactionDetails(Tag):                                                  
                                                                                
    '''Transaction details                                                      
                                                                                
    Pattern: 6x65x                                                              
    '''                                                                         
    id = 86                                                                     
    scope = models.Transaction                                                  
    pattern = r'(?P<transaction_details>[\s\S]{0,330})' 
```
https://github.com/WoLpH/mt940/blob/develop/mt940/tags.py#L310

6x65 != 330; 6x65 is 390.

Is there any reasonable cause for using 330 in that regex?

transaction_details seems are truncated, unfortunately for my mBank stmts, tnr (bank unique id) is at the very end of 86 lines… 86 line are not unicode in my case.

**Comment by WoLpH** [comment]
Yep... quite a silly mistake. I suppose I made a typo while calculating and put in 6*55 instead of 6*65. I've looked through the history and can't find a single valid reason why it would be 330 instead of 390.

**Comment by sq9mev** [comment]
Shouldn't it be 395? Additional 5 for newlines.

**Comment by WoLpH** [comment]
Possibly... and in that case I'm not even sure if the files are always separated by simply a newline or by a newline and a carriage return.

The tests run fine regardless, but that doesn't say much unfortunately
