### ISSUE TITLE
Loads of errors, am I using the wrong fixtures?

### ISSUE THREAD

**Issue by spoetnik** [WoLpH/mt940#4]
I am testing with the testfiles from here: https://github.com/sandermarechal/jejik-mt940/tree/master/tests/Jejik/Tests/MT940/Fixture/document, and I get a lot of errors. I don’t know if those test files are deprecated?
For instance: https://github.com/sandermarechal/jejik-mt940/blob/master/tests/Jejik/Tests/MT940/Fixture/document/abnamro.txt
        parser.py", line 150, in handle_transaction_details
            description, date = details[3].split('TRANSACTIEDATUM*')
        ValueError: need more than 1 value to unpack

and https://github.com/sandermarechal/jejik-mt940/blob/master/tests/Jejik/Tests/MT940/Fixture/document/ing.txt
        parser.py", line 100, in handle_transaction_data
            ''', data, re.VERBOSE).groupdict()
        AttributeError: 'NoneType' object has no attribute 'groupdict'

Python 3.4.0

**Comment by WoLpH** [comment]
Can't say that I've tested with those files, but if that format is still being used than it would be nice to add them to the current test suite :)

The project was written supporting my own ABN-Amro files which worked flawlessly, supporting more would be great but there seems to be no clear/universal standard for MT940 which makes testing a bit of a fix-on-failure thing.

**Comment by WoLpH** [comment]
Looking at those files a bit more closely I notice that most of them are years old... can't say I have too much faith that they're still the same. Especially since the IBAN thing messed up the standards quite a bit.

**Comment by spoetnik** [comment]
Thanks for looking into this. I will try to get my hands on some recent, IBAN, files
