### ISSUE TITLE
Are NS tags actually parsed as intended?

### ISSUE THREAD

**Issue by cluck** [WoLpH/mt940#42]
It seems to me that the NS tags are not parsed as intended. What puzzles me is that there is a unit test actually testing for this unexpected behaviour, so it would be great to get some comments about this.
 
The test file tests/self-provided/raphaelm.sta basically has this structure:

- Transactions
   - `:NS:22Test GmbH` (and more lines)
   - Transaction 1
      - `:NS:01Verwendungszweck 1` (and more lines)
   - Transaction 2-7
      - Some transactions have `:NS:` tags
   - Transaction 8
      - `:NS:01bekannt`, `1812345`

mt940.parse() actually produces this:

- Transactions
   - `:NS:01bekannt`, `1812345`
   - Transaction 1-8
      - No NS records

So there is a clear mismatch of the scopes.

**Comment by WoLpH** [comment]
It appears you're right, it's definitely not storing the data. The expected output for that test file can be found in the `yml` file (should be the same as `mt940.parse()`) and it doesn't mention either of those: https://github.com/WoLpH/mt940/blob/develop/tests/self-provided/raphaelm.yml
