### ISSUE TITLE
Overly long transaction details crash _parse_mt940_details (?)

### ISSUE THREAD

**Issue by sbi** [WoLpH/mt940#47]
I'm investigating a crash while parsing a VR Bank MT940 file. Here's the stack trace:

```
~/my/stuff.py in check_payments(cls, mt940_file)
    568 			and returns a list of result records for each transaction in the mt940 file """
    569                 mt940_data = mt940_file.read().decode('latin1')
--> 570                 transactions = mt940.parse(mt940_data).transactions
    571                 results = []
    572                 for transaction in transactions:

~/somewhere/virtualenv-3.5.4/lib/python3.5/site-packages/mt940/parser.py in parse(src)
     50 
     51     transactions = mt940.models.Transactions()
---> 52     transactions.parse(data)
     53 
     54     return transactions

~/somewhere/virtualenv-3.5.4/lib/python3.5/site-packages/mt940/models.py in parse(self, data)
    369 
    370             for processor in self.processors.get('post_%s' % tag.slug):
--> 371                 result = processor(self, tag, tag_dict, result)
    372 
    373             # Creating a new transaction for :20: and :61: tags allows the

~/somewhere/virtualenv-3.5.4/lib/python3.5/site-packages/mt940/processors.py in transaction_details_post_processor(transactions, tag, tag_dict, result)
    198 
    199     if gvc.isdigit() and int(gvc) in gvcs and details[3:6] == '?00':
--> 200         result.update(_parse_mt940_details(details))
    201 
    202         purpose = result.get('purpose')

~/somewhere/virtualenv-3.5.4/lib/python3.5/site-packages/mt940/processors.py in _parse_mt940_details(detail_str)
    139             continue
    140         tmp[segment_type] = segment if not segment_type else segment[2:]
--> 141         segment_type = detail_str[index + 1] + detail_str[index + 2]
    142         segment = ''
    143 

IndexError: string index out of range
```

The immediate problem is that `detail_str` ends in a question mark. After digging further, I found that `detail_str` contains a truncated version of the data I see in the original MT940 file. I looked at the regex in `TransactionDetails` and I believe it says that a transaction detail field can only have up to six lines, with a max line length of 65. However, the relevant part of the MT940 file looks like this (I changed a few digits in an attempt to hide any private account numbers):

```
:86:105?00Basislastschrift?10931?20EREF+LS-FP2-840-1000-282163
?210623 ?22MREF+POSTAG0053000001669688?23CRED+DE65ZZZ00000210259 
?24PURP+OTHR andere ?25SVWZ+KD9191919195 919191912
?263 REFSAP3147898009/EFI RE74?2763339623  DAT04.10.2017 VIE
?28LEN DANK, IHRE EFILIALE 314?919191919 EREF: LS-FP2-840-10
?30HYVEDEMM?31DE84700202700015179032?32Deutsche Post AG?34992
?6000-2821919123 MREF: POSTAG0?61053000001669688 CRED: DE65Z
?62ZZ00000210259 IBAN: DE84700?63202700015179032 BIC: HYVEDE
```

Is that "out of spec", and can I send a PR to allow for more lines?

**Comment by WoLpH** [comment]
It's definitely out of spec for every MT940 specification file I've seen so far. But if it's out there.. let's fix it :)

Pull requests are more than welcome, assuming they don't break anything else of course :)
Simply run `tox` to test everything (or wait for travis to run after creating the pull request).

**Comment by sbi** [comment]
I modified the max number of lines locally and am running it against 10 months of MT940. Looks good so far, and from what I know about the format the change should not break anything. I hope I can make a pull request later today.

**Comment by WoLpH** [comment]
I expect to be able to review it this weekend, thanks for all the help :)

**Comment by WoLpH** [comment]
Ok... didn't manage that weekend but I've been able to review it now and I've merged your changes.

Thank you so much for all the help!

**Comment by jcpsantiago** [comment]
I'm getting this bug again using version 4.12.2:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-457c9efd8af9> in <module>
      4     pprint.pprint(data)
----> 5     p = mt940.parse(data)
      6 
      7     for transaction in p:

c:\users\edadmin\documents\risk-edzwo\.venv\lib\site-packages\mt940\parser.py in parse(src, encoding)
     64 
     65     transactions = mt940.models.Transactions()
---> 66     transactions.parse(data)
     67 
     68     return transactions

c:\users\edadmin\documents\risk-edzwo\.venv\lib\site-packages\mt940\models.py in parse(self, data)
    417 
    418             for processor in self.processors.get('post_%s' % tag.slug, []):
--> 419                 result = processor(self, tag, tag_dict, result)
    420 
    421             # Creating a new transaction for :20: and :61: tags allows the

c:\users\edadmin\documents\risk-edzwo\.venv\lib\site-packages\mt940\processors.py in transaction_details_post_processor(transactions, tag, tag_dict, result)
    199     # check for e.g. 103?00...
    200     if re.match(r'^\d{3}\?\d{2}', details):
--> 201         result.update(_parse_mt940_details(details))
    202 
    203         purpose = result.get('purpose')

c:\users\edadmin\documents\risk-edzwo\.venv\lib\site-packages\mt940\processors.py in _parse_mt940_details(detail_str)
    139             continue
    140         tmp[segment_type] = segment if not segment_type else segment[2:]
--> 141         segment_type = detail_str[index + 1] + detail_str[index + 2]
    142         segment = ''
    143 

IndexError: string index out of range
```

```
:86:105?00FOLGELASTSCHRIFT?109250?20EREF+31HA07BC81305866B2CA4A?2
1529648D0D2?22MREF+3034.1710.5760?23CRED+DE92XXX12312319957?24SVW
Z+3722.9795.1964 HAFEL-L?25INGPING GMBH CO. KG LEXING?26E RECHNU
NG FINANZEN MONATSP?27REIS GLAUB-ID DE34ZXX123345?644095 ID
A9044ED4-A8876-?ABC123-90D?30PBBBDEFFXXX?31DE9846948540984758434?
32HAFL-LINGPING GMBH CO. KG?34992?60ABWA+HAFEL-LINGPING GMBH CO.?6
```
the complete mt940 has several :61 and :86 chunks, but deleting this one allows mt940.parse to do its job. The :86 is only 6 lines long though, so I'm not sure if I'm looking at the same problem here as @sbi . Running mt940.parse against a large number of transactions has resulted in this error for several of them.

**Comment by WoLpH** [comment]
It looks like you have a similar but different issue. Instead of being out of spec with too many lines it's got too many characters (at least with the last line).

I'll have to investigate what's going on here though. In any case line 141 of processors.py does not look defensive enough in my opinion, assumptions that multiple parts are there can be wrong.

**Comment by jcpsantiago** [comment]
thanks for your answer! I got a couple of examples like the one above, let me know how I can provide help with this issue.

**Comment by WoLpH** [comment]
If you can provide some (anonymized) data files that would help a lot to keep it running in the future. But I think the snippet above should already help :)

**Comment by dr-duplo** [comment]
I got a similar issue, but this time the line ends with a ? without segment type.
A 2 liner could make _parse_mt940_details() a little bit more defensive on that kind of problem- The downside would be to silently miss some data (probably).

Should I make pull request?

**Comment by WoLpH** [comment]
Pull requests are always welcome :)
