### ISSUE TITLE
Missing DETAIL_KEYS for "additional_purpose" in transaction details

### ISSUE THREAD

**Issue by sbi** [WoLpH/mt940#48]
In `mt940.processors._parse_mt940_details`, values for detail keys 20 thru 29 are concatenated since they together constitute the `purpose` field. The [linked spec](https://www.db-bankline.deutsche-bank.com/download/MT940_Deutschland_Structure2002.pdf) says keys 60 thru 63 should likewise be treated as the `additional_purpose` field, however only key 60 is considered. Is that on purpose (no pun intended ;-) , or may I fix it?

**Comment by WoLpH** [comment]
Fixed by your own pull request (#50)
