### ISSUE TITLE
Rabo MT940 extended error.

### ISSUE THREAD

**Issue by spoetnik** [WoLpH/mt940#5]
Parsing Rabo MT940 Structured is giving an exeption:
```
in handle_transaction_data
    ''', data, re.VERBOSE).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
```
https://github.com/WoLpH/mt940/blob/master/mt940/parser.py#L100

See this gist for the file : https://gist.github.com/spoetnik/046c2e9dd4242d2603ad

**Comment by WoLpH** [comment]
Just a little update here, I'm working on handling this but I'm having a bit of trouble deciphering the rabobank format. Perhaps the jejik-mt940 library will help a bit though...

Thanks for the file, helps a lot with testing :)

**Comment by spoetnik** [comment]
Cool thanks. I wish I was so Python-savvy I could help.
Here are the Rabobank specs: https://www.rabobank.nl/images/formaatbeschrijving_swift_bt940s_1_0_nl_rib_29539296.pdf
Have you seen this Ruby parser? https://github.com/railslove/cmxl
Looks like custom MT940 definitions could be handled by overriding a class...

Thanks for looking into this!

**Comment by WoLpH** [comment]
This standard is beyond crappy... that is, there are many standards and apparently most of the banks are not complying with the standards.... A lot more painful than I'd hoped but I've made it a bit more versatile. 

Now it supports any sta file I could find (thanks to your links I now have 32 files which are supported) but it won't have all details for every file. Let me know if you need more help :)

**Comment by spoetnik** [comment]
Thanks! I will test it! So far it's looking good. Update is on pypi already. Sweeeet!!
