### ISSUE TITLE
post processor too eager to strip whitespace

### ISSUE THREAD

**Issue by FelixSchwarz** [WoLpH/mt940#51]
Not sure how to provide the raw test data but I think the processor to parse transaction details is too eager stripping whitespace:

     'transaction_details': '820?00UMBUCHUNG?109392?20ERSTATTUNG '
                            'AUSLANDSEINSATZE?21NTGELT\n'
                            ' FUER VISA 4998 XXXX?22XXXX '
                            '1234?3012030000?319003932309?32DEUTSC\n'
                            'HE KREDITBANK AG'

After processing this with mt940 + python-fints (latest git) I see this:

     'purpose': 'ERSTATTUNG AUSLANDSEINSATZENTGELTFUER VISA 4998 XXXXXXXX 1234',

As you can see in the original data there is a space before "FUER" which should be preserved.

Of course I'm ready to submit additional data and probably I could even come up with some tests but I need some pointers to get started...

**Comment by WoLpH** [comment]
It was a pretty easy fix actually :)

**Comment by FelixSchwarz** [comment]
Ah great, I didn't consider that the existing corpus might contain issues of this :-)

Thanks for fixing it so quickly.
