### ISSUE TITLE
:61: Statement format from Sberbank

### ISSUE THREAD

**Issue by csfulop** [WoLpH/mt940#53]
Hi,
I have STA files from Sberbank which mt940 can not process.
It contains statements like this:
```
:61:1710111011DF2402,00S   X
```
It seems Sberbank does not fill Transaction Type Identification Code.
I have updated its regexp to allow spaces, will send merge request soon.

**Comment by WoLpH** [comment]
I've released a new version thanks to your help. It's much appreciated :)
