### ISSUE TITLE
MT940 structured

### ISSUE THREAD

**Issue by corebyte** [WoLpH/mt940#6]
This is for mt940 structured file right?

I get a name key error in de list ?

Some have the regex name and some not. Do you know a solution?

It is really hard to find a good mt940/mt940 structured parser in Python that works..

**Comment by corebyte** [comment]
![schermafbeelding 2015-04-28 om 14 29 56](https://cloud.githubusercontent.com/assets/6604721/7369542/15014dec-edb3-11e4-9684-df38b338925c.png)

**Comment by WoLpH** [comment]
Thanks for the heads up, after the changes I've made last week these apparently aren't working anymore.

The new release fixes this with 100% test coverage again. Please let me know if you have any problems :)
