### ISSUE TITLE
Improve handling of (strange) encoded statements

### ISSUE THREAD

**Issue by zdenop** [WoLpH/mt940#60]
I need to process "strange" encoded mt940 statements.

Background: Data/statement if from Hungarian RZB, statement is generated by system running in RZB Austria and exported in Slovakia (on Windows 7). chardet suggest to use Turkish encoding for data ;-) 

Basic attempt to use `transactions = mt940.parse('raiffeisen-cmi.sta.txt')` failed:
```
  File "C:\Program Files\Python36\lib\site-packages\mt_940-4.11.0-py3.6.egg\mt940\parser.py", line 52, in parse
    transactions.parse(data)
  File "C:\Program Files\Python36\lib\site-packages\mt_940-4.11.0-py3.6.egg\mt940\models.py", line 400, in parse
    tag_dict = tag.parse(self, tag_data)
  File "C:\Program Files\Python36\lib\site-packages\mt_940-4.11.0-py3.6.egg\mt940\tags.py", line 71, in parse
    self, value)
RuntimeError: ('Unable to parse "<mt940.tags.Statement object at 0x0000015B5FA95080>" from "180417DF14790,00N031\nElektronikus bankon bel\x81li \xa0tutal\xa0s"', <mt940.tags.Statement object at 0x0000015B5FA95080>, '180417DF14790,00N031\nElektronikus bankon bel\x81li \xa0tutal\xa0s')
```

At the moment I use this workaround (it "damages encoding" but I am able to process statement) by function:

```
def sta_data(filename):
    rawdata = open(filename, 'rb').read()
    result = chardet.detect(rawdata)
    charenc = result['encoding']
    return rawdata.decode(charenc, 'ignore')
```

I think it could make sense to solve it at mt940.tags.Statement.
Also it would make sense to implement option "encoding" for file reading or at least to document information about expected file data encoding.

Unfortunately I am not able to attach file to this issue for testing, but I can send it if needed.

**Comment by zdenop** [comment]
OK. So I found correct encoding. It is cp852. 
So there must be bug in tag parsing: when I put there correctly encoded utf-8 string parse fails. If there is asciionly encoded string (created by rawdata.decode(charenc, 'ignore') ) it works...

Test file can be downloaded from http://www.filedropper.com/raiffeisen-cmi

**Comment by WoLpH** [comment]
The `parse` method accepts filenames, file objects or even the data as a string so that should be versatile enough. But it's not unlikely that there are utf-8 issues in the code, I've never (had to) extensively test utf-8 support.

So to open a file with a specific encoding you could do something like this:
```python
import codecs
import mt940

transactions = mt940.parse(codecs.open('transactions_file.sta', encoding='cp852'))
```

Still, valid utf-8 should be parsed without issues so I'll work on that. Thanks for the help :)

**Comment by WoLpH** [comment]
The new release has some automatic encoding detection and properly handles unicode :)
