### ISSUE TITLE
incorrect linebreaks sent by bank

### ISSUE THREAD

**Issue by marcelb98** [WoLpH/mt940#65]
When fetching transactions with the python-fints library the mt940 parser crashes because there are some non-valid line breaks in the MT940 sent by our bank (Ostsächsiche Sparkasse Dresden).

We found the following two types of superfluous line breaks:
1. Line break in a line starting with the `:61:` tag:
```
:61:1811261126CR
30,00N062NONREF
```

2. Line break in the `:86:` tag:
```
:
86:166?00GUTSCHR. UEBERWEISUNG?081542?20SVWZ+Test
```

I know that this isn't an issue of this library. But since contacting our bank resulted in a reference to their banking software and the information that third-party products are not supported, it might be the best solution to accept those line breaks. Maybe also other Sparkassen are affected.

**Comment by WoLpH** [comment]
As long as it doesn't break the parsing for other banks I'm not opposed to a fix for this. But I do wonder where these newlines can occur. Is it always before the amount with the `:61` tag?

As for the newline within the tag... that's a really strange one if you ask me. They most have some really broken software over there :P

Either way, I've attempted to create a fix that doesn't break anything else. Can you test if it works?

**Comment by marcelb98** [comment]
There are not so many transactions which contain these line breaks (I've found 5 in 464 transactions).
But if there's a `:61:` tag containing a superfluous line break it is every time before the amount.

I've tested the broken transactions with the current develop-branch and it's working fine. Thanks 👍
