### ISSUE TITLE
how to display mt940 on a text file with spaces between them

### ISSUE THREAD

**Issue by eben562012** [WoLpH/mt940#66]
hi wolf, used to extract data from mt940 and it works perfectly but i having challenges when it comes to displaying the output to text file like wordpad or notepad. the problem is that when it prints unto the text file created, it comes without space between them-thus no indentation or new line . any help will be much appreciated.

**Comment by WoLpH** [comment]
The thing is... it depends. There are loads of different banks and all of them have different standards. Apparently your bank strips the whitespace between the lines.

Luckily that's in a separate bit of code that can be skipped if you don't need it: 
https://github.com/WoLpH/mt940/blob/49bf578870bb0f5e8fc8d691c12f9f9481122c5e/mt940/processors.py#L195-L210

I think this should do the trick:
```python
import mt940

# copy the default processors
processors = mt940.models.Transactions.DEFAULT_PROCESSORS.copy()
# remove the processor, defined here: https://github.com/WoLpH/mt940/blob/49bf578870bb0f5e8fc8d691c12f9f9481122c5e/mt940/models.py#L254-L256
processors['post_transaction_details'] = []

# initialize the transactions model
transactions = mt940.models.Transactions(processors=processors)

# continue as usual
transactions.parse(...)
```

**Comment by eben562012** [comment]
Wolph i have tried it but am still not getting the result that i want.
there is still no paragraph in the output and moreover too the i can not
find
https://github.com/WoLpH/mt940/blob/49bf578870bb0f5e8fc8d691c12f9f9481122c5e/mt940/models.py#L254-L256,
where i can remove what you showed me. i have look through all my related
python files to see if can find it but i cannot find. any help would be
appreciated.

**Comment by WoLpH** [comment]
Can you send the (anonymized) mt940 file so I can check? It's hard to debug the issue without having an example.

**Comment by eben562012** [comment]
this is a sample file on what am working on

**Comment by WoLpH** [comment]
It looks like the file got lost somewhere, can you try mt940<at>wol.ph ?

**Comment by eben562012** [comment]
what does it mean http://mt940wol.ph/ and i have tried searching but am
blocked. so what should i do? resend it or what. can you specific

**Comment by WoLpH** [comment]
I meant the mail address, looks like the mail client is filtering out some part.

mt940 AT wol.ph

**Comment by eben562012** [comment]
i have added a comment at the link http://wol.ph/ page with name eben. hope
this helps rather than using mail

**Comment by eben562012** [comment]
{1:FO1SBZAZAJJXXXX999999999}{2:I940SBCICMVWMXXXXXN}{4:

:20:ONUMAH SAVINGS AND LOANS
:25:517852257
:28:19321/1
:60F:C110522EUR3236,28
:60M:C111015M1400
:61:1105240524DS900,N192ONU17
:62F:C18021315500
:86:GIRO   428428 KPN - DIGITENNE    BETALINGSKENM.  000000042188659
5314606715                       BETREFT FACTUUR D.D. 20-05-2011
INCL. 1,44 BTW
-}



{1:FO1SBZAZAJJXXXX999999999}{2:I940SBCICMVWMXXXXXN}{4:
:20:D424A100110011E4
:25:020083203
:28C:49/1
:60F:C140106ZAR1029873, 62
:61:1401060106DR5000, NTRF99999999//NONREF
2014106-13175-016050001844421
:86:/PREF/ZA000520CATS THIRD PARTY PAYMENT
:62F:C140106ZAR0,00
-}


{1:1:FO1SBZAZAJJXXXX999999999}{2:1940SBICMVWMXXXXXN}{4:
:20:D3DE7040110011E4
:25:020083204
:28C:51/1
:60F:C140106NAD1030073,
:61:1401060106DR50001844421
:86:/PREF/NA000520TRANSFER
:62F:C140106NAD0,00
-}










THIS IS THE SAMPLE FILE AM WORKING ON 
{1:1:FO1SBZAZAJJXXXX999999999}{2:1940SBICMVWMXXXXXN}{4:
:20:D3DF8040110011E5
:25:020083205
:28C:40/1
:60F:C140106NAD1030063,
:61:1401060106DR50001844421
:86:/PREF/NA000520TRANSFER
:62F:C160106NAD0,00
-}

**Comment by WoLpH** [comment]
I've tried the code I showed earlier and it appears to work as expected. The newlines are left intact. What output are you expecting?
```python
import mt940

# copy the default processors
processors = mt940.models.Transactions.DEFAULT_PROCESSORS.copy()
processors['post_transaction_details'] = []

# initialize the transactions model
transactions = mt940.models.Transactions(processors=processors)

# continue as usual
for transaction in transactions.parse(open('test.mt940').read()):
    print('Transaction:', transaction)
    print(transaction.data['transaction_details'])
```
