### ISSUE TITLE
ValueError: stat: path too long for Windows

### ISSUE THREAD

**Issue by arielszeloch** [WoLpH/mt940#68]
An error pop-up once trying to pass string like `mt940.parse(f.read())`
In line 44 is a check:
`elif os.path.isfile(src):`
which crach once provide str under Windows.

Solution is to move it after: `elif hasattr(src, 'decode'):`

fixed code looks like:
```
if hasattr(src, 'read'):  # pragma: no branch
        data = src.read()
    elif hasattr(src, 'decode'):
        exception = None
        encodings = [encoding, 'utf-8', 'cp852', 'iso8859-15', 'latin1']

        for encoding in encodings:  # pragma: no branch
            if not encoding:
                continue

            try:
                data = src.decode(encoding)
                break
            except UnicodeDecodeError as e:
                exception = e
        else:  # pragma: no cover
            raise exception
    elif os.path.isfile(src):
        return parse(open(src, 'rb').read())
    else:  # pragma: no cover
        data = src
```

**Comment by WoLpH** [comment]
The problem with that is that a filename is a regular string so it also has a `decode` attribute. So changing the order changes the behaviour

What kind of error are you receiving exactly? Perhaps it can be fixed through a try/except instead?

**Comment by arielszeloch** [comment]
Getting an error as it is in the topic: `ValueError: stat: path too long for Windows`

I am not opening a file, I am providing string as a parameter. Once doing that string doesnt have `decode` attribute so first `if` is skipped. Which is correct.

Next one in original code is: `elif os.path.isfile(src):` and python is trying to check is it a file (I didnt activated long path in python instalation wizard) and script crash at this step as trying to parse long string as path.

In my case it should be handle by 3rd part of check which is: `elif hasattr(src, 'decode'):` this is why I have changed an order for time beeing to fix an error.

actually it found `decode` attribute in string and never tried to check is it a file.

I agree it can be handled by `try/except` and probably it is a better idea.

**Comment by WoLpH** [comment]
Oops... forgot about the title :)

I've released a new version that incorporates the fix. Can you verify if it works for you?
