### ISSUE TITLE
Don't install `tests` as a global python package

### ISSUE THREAD

**Issue by lukasjuhrich** [WoLpH/mt940#78]
The current `setup.py` configuration results in `tests` being shipped as a python package (the [`find_packages` call](https://github.com/WoLpH/mt940/blob/develop/setup.py#L102) only excludes `docs/`).

This implies that everyone installing `mt940`, or any package which depends on `mt940` (like `fints`), is now unable to use `import tests` to access their own `tests/` package without manual `importlib` intervention. In particular, this renders usage of `nosetest` impossible.

**Comment by WoLpH** [comment]
Good point, I'll release a fix soon. This might not be my only package suffering from this issue

**Comment by WoLpH** [comment]
I've uploaded a new release to PyPI :)

**Comment by MaicoTimmerman** [comment]
@WoLpH I believe somehow this issue is still present. 

I've installed a fresh virtual environment and install the latest version:
```bash
python -m virtualenv venv
source venv/bin/activate
pip install mt-940==4.23.0
ls venv/lib/python3.10/site-packages/tests
```
shows the following content:
```
betterplace/  conftest.py  jejik/  __pycache__/  self-provided/       test_metadata.py  test_processors.py   test_tags.py
cmxl/         __init__.py  mBank/  sberbank/     test_entry_dates.py  test_parse.py     test_sta_parsing.py  test_utils.py
```
Comparing `tests` and `mt940_tests`, I believe these might be leftover local changes that have been included during packaging:
```
diff -q venv/lib/python3.10/site-packages/tests/ venv/lib/python3.10/site-packages/mt940_tests/
Common subdirectories: venv/lib/python3.10/site-packages/tests/betterplace and venv/lib/python3.10/site-packages/mt940_tests/betterplace
Common subdirectories: venv/lib/python3.10/site-packages/tests/cmxl and venv/lib/python3.10/site-packages/mt940_tests/cmxl
Files venv/lib/python3.10/site-packages/tests/conftest.py and venv/lib/python3.10/site-packages/mt940_tests/conftest.py differ
Common subdirectories: venv/lib/python3.10/site-packages/tests/jejik and venv/lib/python3.10/site-packages/mt940_tests/jejik
Common subdirectories: venv/lib/python3.10/site-packages/tests/mBank and venv/lib/python3.10/site-packages/mt940_tests/mBank
Common subdirectories: venv/lib/python3.10/site-packages/tests/__pycache__ and venv/lib/python3.10/site-packages/mt940_tests/__pycache__
Common subdirectories: venv/lib/python3.10/site-packages/tests/sberbank and venv/lib/python3.10/site-packages/mt940_tests/sberbank
Common subdirectories: venv/lib/python3.10/site-packages/tests/self-provided and venv/lib/python3.10/site-packages/mt940_tests/self-provided
Files venv/lib/python3.10/site-packages/tests/test_parse.py and venv/lib/python3.10/site-packages/mt940_tests/test_parse.py differ
Files venv/lib/python3.10/site-packages/tests/test_processors.py and venv/lib/python3.10/site-packages/mt940_tests/test_processors.py differ
Files venv/lib/python3.10/site-packages/tests/test_tags.py and venv/lib/python3.10/site-packages/mt940_tests/test_tags.py differ
```

Apart from that, I also feel like shipping and packaging `mt940_test` test directory is considered good practice and should be added to the excludes:
https://github.com/WoLpH/mt940/blob/d3f8b44f26b220f5bf97bf448f8960efe4278d3f/setup.py#L98

**Comment by WoLpH** [comment]
You're right. There was something wrong with the old file. I've since switched to a new build system and I've pushed a new release so this will never happen again... I hope ;)
