### ISSUE TITLE
Parse GV codes when purpose does not start with GV codes

### ISSUE THREAD

**Issue by bdabelow** [WoLpH/mt940#79]
Some banks use GV codes in the purpose field, but do not start the data with them:
```
'purpose': 'Cie., S.C.A.SEPA-BASISLASTSCHRIFTEREF+ 1234567890123 PAYPALMREF+ 12AB234CD6E7F CRED+ AB12CDE0000000000000000034 SVWZ+ . SPOTIFY, Ihr Einkaufbei SPOTIFY'
```

In this case the GV codes are not parsed at the moment, because purpose is expected to start with a GV code:
```
if purpose and purpose[:4] in GVC_KEYS:  # pragma: no branch
    result.update(_parse_mt940_gvcodes(result['purpose']))
```

In my personal use parsing is fine when doing it unconditionally:
```
if purpose:  # pragma: no branch
    result.update(_parse_mt940_gvcodes(result['purpose']))
```

This breaks a number of tests that I have not looked into, yet.

What would be a preferred solution for this situation?

- Parse GV codes unconditionally
- Parse when GV code is found anywhere in purpose
- Make behavior configurable/separate processor
- ???

I would be willing to prepare a PR when agreed on a way forward.

**Comment by WoLpH** [comment]
Thanks for the detailed issue, always appreciated! 

Option 2 seems the best to me, but as long as it doesn't break anything I wouldn't object to option 1 either.

I hardly think performance is a large factor for this library so the overhead is probably not a problem.

It would be great if you're willing to create a pull request, any help is appreciated.

**Comment by bdabelow** [comment]
Thanks for merging.
