### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by kellerkind** [WoLpH/mt940#81]
Seems the current parsing for this library changed slightly.

Instead of `mt940.parse` I need to use a class:

```
obj = mt940.MT940("Downloads/20200110-1631282804-umsMT940.TXT")
```
This fails with missing positional parameter:

```
TypeError: __new__() missing 1 required positional argument: 'end_balance'
```

Question is what is the format of the `end_balance` parameter?

I tried with `datetime` and `datetime.isoformat()` but both failed.

**Comment by WoLpH** [comment]
The library is generally pretty stable in terms of usage so most code that worked before should still work :)

As far as I can remember there's never been a `mt940.MT940(...)` class so I think you previously used a different library.

**Comment by kellerkind** [comment]
Thanks for your response.
Your are corrct, it seems a similar spelled package exists on pypi:

pip list:
```
mt940            0.4
```
