### ISSUE TITLE
The ASN bank MT940 file can not be parsed for tag 61

### ISSUE THREAD

**Issue by gpaulissen** [WoLpH/mt940#82]
The tag 61 from the ASNB bank has a format for tag 61 which is not conform the Swift specifications. They use the IBAN (34x) for customer reference (16x). See attachment example.

From: https://www.sepaforcorporates.com/swift-for-corporates 

    Pattern: 6!n[4!n]2a[1!a]15d1!a3!c16x[//16x]
[34x]

    But ASN bank puts the IBAN in the customer reference, which is acording to
    Wikipedia at most 34 characters.

    So this is the new pattern:

    Pattern: 6!n[4!n]2a[1!a]15d1!a3!c34x[//16x]
[34x]

[0708271685_09022020_164516.940.txt](https://github.com/WoLpH/mt940/files/4298644/0708271685_09022020_164516.940.txt)

**Comment by WoLpH** [comment]
Thank you for the help. I've created a new release which has your changes incorporated.

Fixed in #83
