### ISSUE TITLE
Parsing transactions : key 64

### ISSUE THREAD

**Issue by elisaprio** [WoLpH/mt940#85]
Hello
First thank you so much for this parser !

In `result.get("additional_purpose","").replace("\r\n"," ")` key ?64 is missing. It's a part of the address. Could it be added in "additional_purpose" field ?

And for those address related keys, could spaces be added between each key (for example write something like `result[key60] = f"{result[key60] or ''} {value}"` instead of `result[key60] = (result[key60] or '') + value` ) in order to facilitate future address parsing ?

Thank you in advance for your work,

Elisa

**Comment by WoLpH** [comment]
The `additional_purpose` gets parsed by the `transaction_details_post_processor`:
https://github.com/WoLpH/mt940/blob/ecb8c9fb31267a90780a279c40c2af1ea8c95d1e/mt940/processors.py#L198-L214

If you would add an extra post processor in `post_transaction_details` you could get it parsed. It's probably something specific for your bank:

```python
import mt940
import pprint

mt940.tags.BalanceBase.scope = mt940.models.Transaction

# The currency has to be set manually when setting the BalanceBase scope to Transaction.
transactions = mt940.models.Transactions(processors=dict(
    post_transaction_details=[
        <your processors>
    ],
))

with open('filename.sta') as f:
    data = f.read()

transactions.parse(data)

for transaction in transactions:
    print('Transaction: ', transaction)
    pprint.pprint(transaction.data)
```

**Comment by elisaprio** [comment]
Hi
Thanks for your quick answer.

Sorry I realised I pasted the wrong thing in my message yesterday. I meant in the method `_parse_mt940_details` there is a test `elif key in ('61', '62', '63')` but when I read some documentation related to mt940 extended format, I see that for tag 86 "information to account owner" it goes from 60 to 65. I read that in [multine doc](https://www.multiline.lu/fileadmin/media/downloads/MT940_V2_fr.pdf) but it's only available in french. Other banks documentation also talk about thoses keys.
So I believe subkeys ?64 and ?65 are not parsed. So data is missing for the key _additional_purpose_ in my parsed Transactions() object.
To do the parsing, I use the parse method from Transactions model.

Do you think it's possible to fix that, since I don't think it's specific to my bank but to mt940 extended format ? I think it's somehow the same problem as for this PR : #48

**Comment by WoLpH** [comment]
I've created a new release that has this fix. Can you check if it works for you @elisaprio?

Sorry for the slow response, I've been really busy so it's hard to find time

**Comment by elisaprio** [comment]
Thank you so much ! This will work for me. Do you think it would  be also be possible to add a blank space before adding the new value ? Or is it unwise ?
Something like : `result[key60] = f"{result[key60] or ''} {value}"` instead of `result[key60] = (result[key60] or '') + value`

And sorry for the late reply too ! So no problem for the time =)

**Comment by WoLpH** [comment]
The problem is (and with the entire standard in general) that nearly every bank has its own interpretation of the standard. While it might fix it for your bank, it will breakt it for some others.

I can add it as a configurable option though, from what I see in my tests there's not single testfile that currently has a format where it makes a difference though. Do you have an example file by any chance?

**Comment by WoLpH** [comment]
Looks like there was actually 1 file that used this (and doesn't need the space).

You can use the version with spaces like this: https://github.com/WoLpH/mt940/blob/2e3669f9f0fd77abd5f4d5e58fe26b27f7620b40/mt940_tests/test_processors.py#L93-L97

**Comment by elisaprio** [comment]
Thank you so much ! It works perfectly for me !!
Here is the file I use for my tests : 
[CCPM940EB20191025_215418_158_MULTILIE191025.dat_12_70855463.zip](https://github.com/WoLpH/mt940/files/4850142/CCPM940EB20191025_215418_158_MULTILIE191025.dat_12_70855463.zip)

**Comment by BeastOfBodmin** [comment]
> Looks like there was actually 1 file that used this (and doesn't need the space).
> 
> You can use the version with spaces like this:
> 
> https://github.com/WoLpH/mt940/blob/2e3669f9f0fd77abd5f4d5e58fe26b27f7620b40/mt940_tests/test_processors.py#L93-L97

I realise this is a "How to use python" question, but how do I get at the results of the post_transaction_details?

```
import mt940
import pprint

# https://github.com/WoLpH/mt940/issues/85
transactions = mt940.parse('1591139129348.STA', processors=dict(
   post_transaction_details=[
        mt940.processors.transaction_details_post_processor,
   ],
))

for transaction in transactions:
    pprint.pprint(transactions.post_transaction_details)
```

results in

```
Traceback (most recent call last):
  File "mt940-test.transaction_details.py", line 16, in <module>
    pprint.pprint(transactions.post_transaction_details)
AttributeError: 'Transactions' object has no attribute 'post_transaction_details'
```
