### ISSUE TITLE
Getting only single account data instead of multiple accounts

### ISSUE THREAD

**Issue by kaifkhan281** [WoLpH/mt940#91]
I'm trying to fetch the accounts and transactions data from a file but I'm facing 2 issues listed below.

1. In our file there are some extra data named checksum and this is causing issue, but after removing the checksum lines I'm also not getting correct data explained in point 2.

2. Only last transaction's account information is coming and all the other transactions data are coming under this single account. 

I have tried all of your 3 processes, getting same issue in all.

Sample file with checksum:
[Sample_BT_Test.txt](https://github.com/WoLpH/mt940/files/7525462/Sample_BT_Test.txt)

Sample file without checksum:
[Sample_BT_Test_Checksum.txt](https://github.com/WoLpH/mt940/files/7525463/Sample_BT_Test_Checksum.txt)

Output JSON file:
[output.txt](https://github.com/WoLpH/mt940/files/7525507/output.txt)

Here you can see all the transactions data are coming in one single account.

Please help and guide to identify and fix the issue.

**Comment by ssebastian90** [comment]
Hello!

How was this completed? I'm facing the same problem. Under "account_identification" field I only see the last account 

Regards
