### ISSUE TITLE
Non-numeric statement number

### ISSUE THREAD

**Issue by not7cd** [wolph/mt940#92]
Hi, I encountered error while parsing statements from polish bank.

```
RuntimeError: ("Unable to parse <mt940.tags.StatementNumber object at 0x7f359f603730> from '09/2021/M'", <mt940.tags.StatementNumber object at 0x7f359f603730>, '09/2021/M')
```

It seems that they are also inconsistent with their own spec which says that StatementNumber follows this pattern
```
:28C:0668-2019/BPL
```

While actual data privdes this 
```
:28C:09/2021/M
```

Can I somehow bypass this, or maybe define my own tag parsers?

**Comment by WoLpH** [comment]
That's an odd format indeed. With regards to fixing it, I can think of two options:
1. Use a pre-processor to convert the value into something the parser can handle
2. Monkeypatch `tags.StatementNumber.pattern` so it matches this data

The pre-processor is the cleaner solution, but I think patching the pattern might be an easier solution here.

**Comment by not7cd** [comment]
This issue has bitten me again. How can I monkey patch this?
