### ISSUE TITLE
Exporting to tabular format

### ISSUE THREAD

**Issue by DavMrc** [wolph/mt940#93]
Hi WoLpH
I was wondering: how would I be able to parse the result of the conversion of a file to a tabular format (pandas, csv, xlsx) and alike?

**Comment by WoLpH** [comment]
The main issue would be that the mt940 format isn't strictly 2 dimensional and doesn't have a fixed amount of columns, meaning that you would get an xlsx with multiple tabs or multiple csv files. But more worrisome is that some rows could have more columns than others.

Having that said... in most cases you can get away with a simple 2D structure though :)
```python
import csv
import mt940

transactions = mt940.parse('mt940-file.sta')

with open('mt940.csv', 'w', newline='') as fh:
    writer = csv.DictWriter(fh, fieldnames=transactions[0].data)
    writer.writeheader()

    for transaction in transactions:
        writer.writerow(transaction.data)
```
