### ISSUE TITLE
Statement line is parsed incorrectly for customer/bank reference

### ISSUE THREAD

**Issue by sshishov** [wolph/mt940#96]
The statement line like this is parsed incorrectly:
```
:61:2001010101DR59,73FCHGTRF SVC//200101ZCPB067071
```

The customer_reference and bank_reference populated incorrectly:
```python
{
    'customer_reference': 'TRF SVC//200101Z',
    'bank_reference': None,
    'extra_details': 'CPB067071',
}
```

It should be parsed like:
```python
{
    'customer_reference': 'TRF SVC',
    'bank_reference': '200101ZCPB067071',
    'extra_details': None,
}
```

**Comment by sshishov** [comment]
@wolph , thank you for merging and maintaining the project. I would like to ask when we can have the next release with these changes?

**Comment by wolph** [comment]
Sorry for the slow release. My laptop had to go back for repairs and I don't have another machine set up for releasing to Github :)
