### ISSUE TITLE
MT940 Issues parsing with :61:

### ISSUE THREAD

**Issue by JonathanNEMRY** [wolph/mt940#99]
When using mt940.parse we have this issue

RuntimeError: ("Unable to parse <mt940.tags.Statement object at 0x7ff52e07da30> from '2212191220C119,NMSC341241773/1XXXXX//O/341241774\\nPaiement'", <mt940.tags.Statement object at 0x7ff52e07da30>, '2212191220C119,NMSC341241773/1XXXXX//O/341241774\nPaiement')

--> Seems that this line is under two line with a carrage return...I don't know if this is problematic but can you help us to solve this? thanks

**Comment by wolph** [comment]
The big question is always what all of the numbers mean here. You can see what the regex is parsing here for reference: https://regex101.com/r/7J7El8/1

Do you have any documentation from your bank to indicate how they build these strings?

**Comment by JonathanNEMRY** [comment]
@wolph  thanks you very much yes the bank give us this file I think it comes from the carrage return that incldes sub lines
[MT940_V2_fr.pdf](https://github.com/wolph/mt940/files/10323535/MT940_V2_fr.pdf)

**Comment by wolph** [comment]
It took a pretty hacky regular expression, but the current version still works with all old tests but also supports the `/` in the customer reference that Multiline uses.

Give the new release a try and let me know if it works for you :)
